import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api,queryKeys} from '@haven/api-client';
import {Button,ErrorState,Loading,Panel,Badge} from '@haven/ui';
export function Support(){
 const q=useQuery({queryKey:queryKeys.victim,queryFn:api.victimHome});const [book,setBook]=useState(false);const [submitted,setSubmitted]=useState(false);
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState message={q.error.message} onRetry={()=>void q.refetch()}/>;const data=q.data;
 return <div className="victim-page"><div className="victim-page__heading"><div><div className="eyebrow">My Support</div><h1>Support around you</h1><p className="muted">Counseling, check-ins and practical requests in one place.</p></div><Button onClick={()=>setBook(value=>!value)}>{book?'Close booking':'Book a session'}</Button></div>{book&&<section className="victim-card victim-booking"><div><div className="eyebrow">Three simple steps</div><h2>Request a counseling session</h2><p className="muted">This demo records your preference locally; a real service will confirm availability.</p></div><div className="victim-booking__choices"><label>Format<select className="victim-input"><option>Voice</option><option>Text</option><option>In person</option></select></label><label>Preferred time<select className="victim-input"><option>Tomorrow afternoon</option><option>This week</option><option>Next available</option></select></label></div><Button onClick={()=>{setSubmitted(true);setBook(false)}}>Send request</Button></section>}{submitted&&<div className="victim-notice" role="status">Your counseling request is recorded in this demo. A human counselor would confirm the next step.</div>}<div className="victim-support-grid"><Panel title="Next counseling conversation"><Badge>{data.appointment.mode.toLowerCase()}</Badge><h2>{data.appointment.counselorName}</h2><p className="muted">{new Date(data.appointment.startsAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})} IST</p><Button>Reschedule</Button></Panel><Panel title="Requests and assistance">{data.support.map(item=><div className="victim-support-row" key={item.id}><div><strong>{item.title}</strong><p className="muted">Support request</p></div><Badge>{item.status}</Badge></div>)}</Panel></div></div>;
}
