import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {api,queryKeys} from '@haven/api-client';
import {Panel,Loading,ErrorState} from '@haven/ui';
import {AuthorityPageHeader,PriorityBadge,StatusBadge,formatDateTime} from './AuthorityShared';
const exceptions=['DELIVERY_FAILED','ACK_OVERDUE','FALLBACK_SENT','ESCALATION_FAILED'];
export function AlertCentre(){
 const q=useQuery({queryKey:queryKeys.tasks,queryFn:api.authorityTasks});
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState message={q.error.message} onRetry={()=>void q.refetch()}/>;
 const urgent=q.data.filter(item=>item.task.priority==='A0'||item.task.priority==='A1').length,issues=q.data.filter(item=>exceptions.includes(item.task.status)).length,sent=q.data.filter(item=>item.task.status==='SENT').length;
 return <><AuthorityPageHeader eyebrow="Maharashtra / Pune · District alert centre" title="Alert centre">Review authority alerts that require human acknowledgement or operational response. Delivery status and delivered assistance are separate.</AuthorityPageHeader><section className="grid authority-summary-grid" aria-label="Alert summary"><Panel title="A0/A1 urgent alerts"><div className="stat">{urgent}</div><p className="muted">Emergency life-safety or immediate-protection work.</p></Panel><Panel title="Delivery exceptions"><div className="stat">{issues}</div><p className="muted">Failed, overdue, fallback, or escalation-failed alerts.</p></Panel><Panel title="Sent alerts"><div className="stat">{sent}</div><p className="muted">Awaiting a human acknowledgement.</p></Panel></section><Panel title="District alert queue">{q.data.length===0?<p className="muted">No alerts are available in this district scope.</p>:<div className="table-wrap" tabIndex={0}><table><caption>Role-filtered district alerts</caption><thead><tr><th scope="col">Alert</th><th scope="col">Classification</th><th scope="col">State</th><th scope="col">Deadline</th><th scope="col">Owner</th></tr></thead><tbody>{q.data.map(item=><tr key={item.task.id}><th scope="row"><Link className="authority-task-link" to={'/authorities/district/tasks/'+item.task.id}>{item.task.title}<span className="authority-docket muted">{item.case.docket}</span></Link></th><td><PriorityBadge value={item.task.priority}/></td><td><StatusBadge value={item.task.status}/></td><td>{formatDateTime(item.task.dueAt)}</td><td>{item.task.owner}</td></tr>)}</tbody></table></div>}</Panel><Panel title="Crisis context"><p className="muted">Current danger facts, location, language, responder details, and delivery receipts are shown only when supplied by the district response. This fixture does not expose those additional fields.</p></Panel></>;
}