import {Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Legend,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {useQuery} from '@tanstack/react-query';
import {api,queryKeys} from '@haven/api-client';
import {priorityLabels} from '@haven/contracts';
import {Panel,Loading,ErrorState} from '@haven/ui';

const tierColors:Record<string,string>={A0:'#b42318',A1:'#d97706',A2:'#0f766e',A3:'#125d87',A4:'#6d5bd0',A5:'#52627a'};
function DataTable({caption,headers,rows}:{caption:string;headers:string[];rows:(string|number)[][]}){return <details className="authority-chart-data"><summary>View chart data</summary><div className="table-wrap" tabIndex={0}><table><caption>{caption}</caption><thead><tr>{headers.map(header=><th scope="col" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=>cellIndex===0?<th scope="row" key={cellIndex}>{cell}</th>:<td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div></details>;}
export function DistrictRiskCharts(){
 const q=useQuery({queryKey:queryKeys.districtAnalytics,queryFn:api.districtAnalytics});
 if(q.isPending)return <section className="authority-chart-section"><Loading/></section>;
 if(q.isError)return <section className="authority-chart-section"><ErrorState message={q.error.message} onRetry={()=>void q.refetch()}/></section>;
 const data=q.data;
 const tiers=data.riskTiers.map(item=>({tier:item.tier,label:item.tier+' — '+priorityLabels[item.tier],count:item.count,color:tierColors[item.tier]}));
 const response=data.responseTimes.map(item=>({tier:item.tier,label:item.tier,average:item.averageAcknowledgementMinutes,target:item.targetMinutes}));
 const responseTarget=response.find(item=>item.tier==="A1")?.target??30;
 const responseAxisMaximum=Math.max(45,Math.ceil((Math.max(responseTarget,...response.map(item=>item.average??0))+5)/15)*15);
 return <section className="authority-chart-section" aria-labelledby="district-statistics">
  <div className="authority-chart-heading"><p className="eyebrow">District operational statistics</p><h2 id="district-statistics">Priority, threat, response and coverage signals</h2><p className="muted">{data.period} · Updated {new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:data.timeZone}).format(new Date(data.updatedAt))} {data.timeZone}. All values are synthetic aggregate demo data.</p></div>
  <div className="authority-advanced-chart-grid">
   <Panel title="1. Authority classification distribution"><p className="muted">Active authority tasks by A0–A5 classification.</p><div className="authority-chart"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={tiers} margin={{top:4,right:18,left:100,bottom:4}}><CartesianGrid horizontal={false} strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="tier"/><Tooltip/><Bar dataKey="count" name="Active tasks" radius={[0,5,5,0]}>{tiers.map(item=><Cell fill={item.color} key={item.tier}/>)}</Bar></BarChart></ResponsiveContainer></div><DataTable caption="Authority classification distribution" headers={['Classification','Active tasks']} rows={tiers.map(item=>[item.label,item.count])}/></Panel>
   <Panel title="2. Urgent-task trend"><p className="muted">A0/A1 task volume and acknowledgement performance across the synthetic replay.</p><div className="authority-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trend} margin={{top:8,right:8,left:-20,bottom:4}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="period"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Area type="monotone" dataKey="openUrgentTasks" name="Open A0/A1 tasks" stroke="#b45309" fill="#f6c66a" fillOpacity={.35}/><Area type="monotone" dataKey="acknowledgedWithinTarget" name="Acknowledged within demo target" stroke="#17633b" fill="#7ecb9b" fillOpacity={.22}/><Area type="monotone" dataKey="acknowledgementOverdue" name="Acknowledgement overdue" stroke="#b42318" fill="#ef9a9a" fillOpacity={.2}/></AreaChart></ResponsiveContainer></div><DataTable caption="Urgent task trend" headers={['Period','Open A0/A1','Within demo target','Overdue']} rows={data.trend.map(item=>[item.period,item.openUrgentTasks,item.acknowledgedWithinTarget,item.acknowledgementOverdue])}/></Panel>
   <Panel title="3. Acknowledgement response time"><p className="muted">Average acknowledgement time compared with configured demonstration targets; not statutory SLA values.</p><div className="authority-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={response} margin={{top:8,right:8,left:-20,bottom:4}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis allowDecimals={false} width={42} domain={[0,responseAxisMaximum]}/><Tooltip/><Legend/><Bar dataKey="average" name="Average acknowledgement (minutes)" fill="#125d87" radius={[5,5,0,0]}/><ReferenceLine y={responseTarget} stroke="#b42318" strokeDasharray="4 4" label={{value:String(responseTarget)+" min demo target",position:"insideTopRight",fill:"#b42318",fontSize:11}}/></BarChart></ResponsiveContainer></div><DataTable caption="Acknowledgement response times" headers={['Tier','Average minutes','Demo target minutes']} rows={response.map(item=>[item.tier,item.average??'No observations',item.target])}/></Panel>
   <Panel title="4. Sub-district workload"><p className="muted">Synthetic administrative blocks only; no map or identifiable location information is shown.</p><div className="authority-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.subdivisions} margin={{top:8,right:8,left:-20,bottom:4}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="openUrgentTasks" name="Open A0/A1 tasks" fill="#b45309" radius={[5,5,0,0]}/><Bar dataKey="openTasks" name="All open authority tasks" fill="#125d87" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><DataTable caption="Sub-district workload" headers={['Administrative block','Open A0/A1','All open tasks']} rows={data.subdivisions.map(item=>[item.name,item.openUrgentTasks,item.openTasks])}/></Panel>
  </div>
 </section>;
}