import {useParams,Link} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api,queryKeys} from '@haven/api-client';
import {Panel,Button,Loading,ErrorState} from '@haven/ui';
import {AuthorityPageHeader,PriorityBadge,StatusBadge,formatDateTime} from './AuthorityShared';
export function DistrictTaskDetail(){
 const {taskId=''}=useParams(),client=useQueryClient();const q=useQuery({queryKey:queryKeys.tasks,queryFn:api.authorityTasks});const mutation=useMutation({mutationFn:api.acknowledge,onSuccess:()=>client.invalidateQueries({queryKey:queryKeys.tasks})});
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState message={q.error.message} onRetry={()=>void q.refetch()}/>;
 const item=q.data.find(entry=>entry.task.id===taskId);
 if(!item)return <section className="panel"><h1>Task unavailable</h1><p className="muted">This task is not available in the current district scope.</p><Link className="authority-inline-link" to="/authorities/district/interventions">Return to intervention queue</Link></section>;
 const canAcknowledge=item.task.status==='SENT';
 return <><nav className="authority-breadcrumb" aria-label="Breadcrumb"><Link to="/authorities/district">District operations</Link><span aria-hidden="true">/</span><Link to="/authorities/district/interventions">Intervention queue</Link><span aria-hidden="true">/</span><span>Task detail</span></nav><AuthorityPageHeader eyebrow={item.case.district+' / '+item.case.state+' · '+item.case.docket} title={item.task.title}>Authority classification is task-specific and does not label a person’s permanent level of risk.</AuthorityPageHeader><div className="authority-detail-layout"><div><Panel title="Task decision context"><div className="authority-badges"><PriorityBadge value={item.task.priority}/><StatusBadge value={item.task.status}/></div><dl className="authority-definition-list"><div><dt>Reason for task</dt><dd>{item.task.reason}</dd></div><div><dt>Recommended intervention</dt><dd>{item.recommendation.title}<span className="muted"> — {item.recommendation.reason}</span></dd></div><div><dt>Intervention state</dt><dd><StatusBadge value={item.recommendation.status}/></dd></div><div><dt>Service availability</dt><dd>{item.recommendation.serviceAvailable===null?'Not confirmed':item.recommendation.serviceAvailable?'Available':'Unavailable'}</dd></div></dl></Panel><Panel title="Facts and uncertainty"><p>The task reason and recommendation above are the only supporting operational facts in this response.</p><p className="muted">Source statements, uncertainty notes, previous attempts, and escalation history are not supplied. They remain unknown rather than assumed absent.</p></Panel><Panel title="Case reference"><dl className="authority-definition-list authority-definition-list-compact"><div><dt>Docket</dt><dd>{item.case.docket}</dd></div><div><dt>Operational district</dt><dd>{item.case.district}, {item.case.state}</dd></div><div><dt>Case process</dt><dd>{item.case.stage}</dd></div></dl></Panel></div><aside className="authority-detail-aside"><Panel title="Ownership and deadline"><dl className="authority-definition-list authority-definition-list-compact"><div><dt>Human owner</dt><dd>{item.task.owner}</dd></div><div><dt>Demonstration deadline</dt><dd>{formatDateTime(item.task.dueAt)} IST</dd></div></dl></Panel><Panel title="Next action">{canAcknowledge?<Button disabled={mutation.isPending} onClick={()=>mutation.mutate(item.task.id)}>{mutation.isPending?'Acknowledging…':'Acknowledge task'}</Button>:<p className="muted">This task has already been acknowledged. Acknowledgement does not confirm delivery.</p>}{mutation.isError&&<p className="authority-error" role="alert">{mutation.error.message}</p>}{mutation.isSuccess&&<p className="authority-success" role="status">Acknowledgement recorded in this browser’s demo session.</p>}<p className="muted">Approval, assignment, referral, delivery and closure controls require role-scoped mock mutations.</p></Panel></aside></div></>;
}