import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {api,queryKeys} from '@haven/api-client';
import {priorityLabels} from '@haven/contracts';
import {Panel,Loading,ErrorState} from '@haven/ui';
import {AuthorityPageHeader,PriorityBadge,StatusBadge,formatDateTime} from './AuthorityShared';
export function InterventionQueue(){
 const q=useQuery({queryKey:queryKeys.tasks,queryFn:api.authorityTasks});const [priority,setPriority]=useState('ALL'),[state,setState]=useState('ALL');
 const tasks=useMemo(()=>q.data?.filter(item=>(priority==='ALL'||item.task.priority===priority)&&(state==='ALL'||item.task.status===state))??[],[priority,q.data,state]);
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState message={q.error.message} onRetry={()=>void q.refetch()}/>;
 return <><AuthorityPageHeader eyebrow="Maharashtra / Pune · District intervention queue" title="Intervention queue">Filter and review district authority tasks. A0–A5 classifications identify the task type; they do not label a person’s permanent risk.</AuthorityPageHeader><Panel title="Filter queue"><div className="authority-toolbar"><p className="muted">Filters apply to the role-filtered district task list.</p><div className="authority-filters"><label>Classification<select value={priority} onChange={event=>setPriority(event.target.value)}><option value="ALL">All classifications</option>{['A0','A1','A2','A3','A4','A5'].map(value=><option value={value} key={value}>{value} · {priorityLabels[value]}</option>)}</select></label><label>Alert state<select value={state} onChange={event=>setState(event.target.value)}><option value="ALL">All alert states</option>{Array.from(new Set(q.data.map(item=>item.task.status))).map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label></div></div></Panel><Panel title="Tasks">{tasks.length===0?<div className="authority-empty"><h2>No matching tasks</h2><p className="muted">Adjust or clear the filters to view district tasks.</p></div>:<div className="table-wrap" tabIndex={0}><table><caption>District authority tasks</caption><thead><tr><th scope="col">Task</th><th scope="col">Classification</th><th scope="col">Alert state</th><th scope="col">Intervention</th><th scope="col">Deadline</th><th scope="col"><span className="sr-only">Review</span></th></tr></thead><tbody>{tasks.map(item=><tr key={item.task.id}><th scope="row">{item.task.title}<span className="authority-docket muted">{item.case.docket}</span></th><td><PriorityBadge value={item.task.priority}/></td><td><StatusBadge value={item.task.status}/></td><td>{item.recommendation.title}<span className="authority-docket muted">{item.recommendation.status.replaceAll('_',' ')}</span></td><td>{formatDateTime(item.task.dueAt)}</td><td><Link className="authority-inline-link" to={'/authorities/district/tasks/'+item.task.id}>Review</Link></td></tr>)}</tbody></table></div>}</Panel></>;
}