import {useQuery} from '@tanstack/react-query';
import {api,queryKeys} from '@haven/api-client';
import {Panel,Loading,ErrorState} from '@haven/ui';
import {AuthorityPageHeader,formatDateTime} from './AuthorityShared';
export function MonitoringDashboard({scope}:{scope:'state'|'national'}){
 const q=useQuery({queryKey:queryKeys.monitoring(scope),queryFn:()=>api.monitoring(scope)});
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState message={q.error.message} onRetry={()=>void q.refetch()}/>;
 const data=q.data,level=scope==='state'?'State':'National',regionLabel=scope==='state'?'District':'State';
 return <><AuthorityPageHeader eyebrow={(scope==='state'?'Maharashtra':'India')+' · Aggregate '+level.toLowerCase()+' scope'} title={level+' monitoring'}>Monitor aggregate demand, operational response, and coverage. Individual records require a separately authorized escalation.</AuthorityPageHeader><section className="grid authority-summary-grid" aria-label={level+' monitoring summary'}><Panel title="Monitored victims"><div className="stat">{data.monitoredVictims}</div><p className="muted">Unique people in this synthetic snapshot.</p></Panel><Panel title="Open authority tasks"><div className="stat">{data.openTasks}</div><p className="muted">Tasks, not a count of people.</p></Panel><Panel title="Human acknowledgements"><div className="stat">{data.acknowledgedTasks}</div><p className="muted">Delivery and outcome are separate.</p></Panel><Panel title="Formal escalations"><div className="stat">—</div><p className="muted">No authorized escalation records in this response.</p></Panel></section><div className="authority-monitoring-layout"><Panel title={regionLabel+' comparison'}><div className="table-wrap" tabIndex={0}><table><caption>{data.period}. One synthetic scenario; not population statistics.</caption><thead><tr><th scope="col">{regionLabel}</th><th scope="col">Monitored victims</th><th scope="col">Open tasks</th></tr></thead><tbody>{data.regions.map(region=><tr key={region.name}><th scope="row">{region.name}</th><td>{region.victims}</td><td>{region.openTasks}</td></tr>)}</tbody></table></div></Panel><Panel title="Reporting context"><dl className="authority-definition-list authority-definition-list-compact"><div><dt>Reporting period</dt><dd>{data.period}</dd></div><div><dt>Last update</dt><dd>{formatDateTime(data.updatedAt)} IST</dd></div><div><dt>Coverage and denominator</dt><dd>One repeatable synthetic scenario. Missing or unknown data are not represented as zero.</dd></div><div><dt>Interpretation</dt><dd>Counts are operational signals, not a measure of intervention success.</dd></div></dl></Panel></div></>;
}